//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Programs.DynamicGenericReturnType;

/// <summary>
/// This is a better example and a more preferred way than demo1
/// </summary>
namespace DynamicGenericReturnType2
{
	public class DyanmicGenericReturnDemo2
	{
//		public static void Main(){ start(); }
		
		public static void start(){
			
				Apple apple = AppleFactory.getObject();
				int age = apple.getProp2<int>(Prop.AGE);	//better to explicitly state what type you want returned
				Console.WriteLine(age);
		}
		
	}
}

