//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace TBase
{
	public class Box : Item
	{
		
		public Box (string name):base(name){
		
		}
		
		//alternative to avoid accessing the singleton directly, use controller
		public void openNum(int randomNum){
			//don't do this, it will give you same numbers when looping
			//this method outside of class
			//int rand = pstate.getRandomNum(1,50);
			MainController.numToUser(randomNum);
		}
		
		
		//public Item item {get;set;}
		public Item item {get;set;}
		public void openItem(){
			//give item to the controller handler
			MainController.itemToUser(item);
		}
		
		
	}
}

