//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace TBase
{
	public class Box
	{
	
		PState pstate;
		
		public Box ()
		{
			pstate = PState.Instance;	
		}
		
		public void open(int randomNum){
			//int rand = pstate.getRandomNum(1,50);		//don't do this, it will give you same numbers
			pstate.inventory.Add(randomNum);
		}
		
		
	}
}

