//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace TBase
{
	public static class BoxFactory
	{
		public static Box getObject(){
			Box box = new Box();
			box.item = PState.Instance.itemRepo[0];
			return box;
		}
	}
}

