//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace TBase
{
	public class ItemTemplateFactory : IFactory
	{
		public List<Item> getObjects()
		{
			List<Item> items = new List<Item>();
			for(int i=0; i<10; i++){
				items.Add(new BagItem("item"+i));
			}
			return items;
		}
		
		//not really useful at the moment
		public Item getObject(){
			return new BagItem("defaultItem");
		}
	}
}

