//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace TBase
{
	public static class ItemFactory
	{
		public static List<Item> getObjects()
		{
			List<Item> items = new List<Item>();
			for(int i=0; i<10; i++){
				items.Add(new Item("item"+i));
			}
			return items;
		}
	}
}

