//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections.Generic;

namespace TBase
{
	public class LooDemo
	{
		public static void Main(){ start(); }
		
		public static void start()
		{
			//init
			PState state = PState.Instance;
			Box box = new Box();
			
			//something triggers event
			Random rand = new Random();
			for(int i=0; i<10; i++){
				box.open(rand.Next(1,50));
			}
			
			//pass by reference
			List<int> test = state.inventory;
			test.Add(99);
			
			foreach(int val in test){
				Console.Write(val + ", ");
			}
			
			Console.WriteLine();
			//test the original object
			foreach(int val in state.inventory){
				Console.Write(val + ", ");
			}
		
			
		}
	}
}

