//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Newtonsoft.Json;

namespace TBase
{
	public class LooLoadBinaryDemo
	{
//		public static void Main(){ start(); }
		
		private static void start(){
			
			SaveLoadState.loadDeserializeObject();	//load the pstate by txt
			
			//test state
			string test = JsonConvert.SerializeObject(PState.Instance);
			Console.WriteLine(test);
			
			//add item
			Box box = (Box)new BoxFactory().getObject();
			box.openItem();
			
			//test state
			test = JsonConvert.SerializeObject(PState.Instance);
			Console.WriteLine(test);
			
			//SaveLoadState.save(test);
			
		}
	}
}

