//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace TBase
{
	[System.Serializable]
	public class PStateSaveSerializeable
	{
	
		public string inventory {get; set;}
		public string itemInventory {get; set;}
		
		public PStateSaveSerializeable ()
		{
		}
	}
}

