//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace TBase
{
	public class PState
	{
		private static PState instance = null;
		private static readonly object padlock = new object();
		
		private PState ()
		{
			//init all repos
			inventory = new List<int>();
			itemInventory = new List<Item>();
			itemTemplateRepo = new ItemTemplateFactory().getObjects();
			Console.WriteLine("PState alive");
		}
		
		public static PState Instance {
		
			get{
				lock(padlock){
					if(instance == null){
						instance = new PState();
					}
					return instance;
				}
			}
			
		}
		
		//states
		public List<int> inventory {get; set;}
		
		public List<Item> itemInventory {get; set;}
		
		public List<Item> itemTemplateRepo {get;set;}
		
		//methods
		//factory calls this, it returns the item template from repo
		public Item getItem(){
			Random rand = new Random();
			return itemTemplateRepo[rand.Next(0, itemTemplateRepo.Count-1)];
		}
		
	}
}

