//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace MyUtilLibrary
{
	public class MyClass
	{
		public MyClass ()
		{
		}
		
		public int add(int x, int y){
			return x+y;
		}
	}
}

