//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Programs.DynamicGenericReturnType
{
	public static class AppleFactory
	{
		public static Apple getObject(){
			Apple e = new Apple();
			e.setProp(Prop.NAME, "Tom");
			e.setProp(Prop.AGE, 5);
			e.setProp(Prop.SPEED, 1.4f);
			
			return e;
		}
	}
}

