//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Randomize
{
	public class RandomDemo
	{
//		public static void Main(){ start(); }
		
		private static void start(){
			Random rand = new Random();
			
			//ex1
			int num = rand.Next(10,20);			//11-19
			int num2 = rand.Next(10,20);
			Console.WriteLine(num + " : " + num2);
			
			//ex2
			int[] arr = new int[10];
			for(int i=0; i<10; i++){
				arr[i] = rand.Next(1,100);
				Console.Write(arr[i] + ",");
			}
			Console.WriteLine(arr.ToString());
			
			
			double d = rand.NextDouble()*2;		//0-2.0
			Console.WriteLine(d);
			
			float f = (float)rand.NextDouble()*5;
			Console.WriteLine(f);
		}
	}
}

