//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Randomize
{
	/// <summary>
	/// shuffles a list of any type into random orders
	/// </summary>
	public static class Shuffle
	{
		public static void shuffle<T>(this IList<T> list) {
			int n = list.Count;
			Random rnd = new Random();
			while (n > 1) {
				//int k = (rnd.Next(0, n) % n);
				int k = rnd.Next(0, n);
				n--;
				T value = list[k];
				list[k] = list[n];
				list[n] = value;
			}
		}
	}
}

