//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;


namespace Serializing
{
	[System.Serializable]
	public class MySaveObject 
	{
		public MySaveObject ()
		{
		}
		
		public string jsonString {get;set;}
		
	}
}

