//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using AliasBase = Inheritance.BaseClass;		//alias

namespace Alias
{
	public class AliasDemo
	{
		
		
		public static void Main(){
			start();
		}
		
		
		private static void start(){
			AliasBase alias = new AliasBase();		//put alias to use
			alias.add(3,3);
			System.Console.ReadKey();
		}
	}
}

