//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Globalization;


namespace Alias
{
	public class ObjectX
	{
	
		public int id {get;set;}
		
		public ObjectX (int id)
		{
			this.id = id;
		}
	}
}

