//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Programs.DynamicGenericReturnType;

namespace Json
{
	public class JsonDemo
	{
		public static void Main(){ start(); }
		
		private static void start(){
			Apple entity = AppleFactory.getObject();
			
			string serialized = JsonConvert.SerializeObject(entity);
			Console.WriteLine(serialized);
			
			//JObject obj = JObject.Parse(serialized);
			//Apple apple = (Apple)JsonConvert.DeserializeObject(serialized);
			
		}
	}
}

