//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace IO
{
	public class IODemo
	{
//		public static void Main(string [] args){
//			start();
//		}
		
		private static void start(){
			string str = System.Console.ReadLine();
			System.Console.WriteLine("my str: " + str);
			Console.ReadKey();
		}
	}
}

